<html>
<head>
	<title>Reinforce'14|About Us</title>
	<style type="text/css">
		*{padding: 0px;	font-family: "calibri";}
		#wrapper
		{
			margin: auto;
			width: 1000px;	min-height: 550px;
			background-color: #ffffff;
			box-shadow: 0px 0px 10px #000000;
			border-radius: 10px;
			overflow: hidden;
		}
		#about_us_wrapper
		{
			width: 700px;
			margin-top: 0px;	margin-left: 70px;
		}
		.about_us_wrapper_elements
		{
			width: 700px;
			margin: 75px auto;
			background-color: #efce03;
			padding: 10px;
			border: 4px solid #ffffff;
			box-shadow: 0px 0px 0px 10px #efce03;
		}
	</style>
</head>
<body>
	<div id="wrapper">
		<?php require("header.inc"); 		?>
		<?php require("navigation.inc");	?>
		<div id="about_us_wrapper">
			<div id="about_fest" class="about_us_wrapper_elements">
				ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US ABOUT US 
			</div>
			<div id="about_srm"  class="about_us_wrapper_elements">
				ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY ABOUT SRM UNIVERSITY 
			</div>
			<div id="about_civil" class="about_us_wrapper_elements">
				ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT ABOUT CIVIL DEPARTMENT 
			</div>	
		</div>	
		<?php require("footer.inc"); 		?>
	</div>
</body>
</html>