<head>
	<style type="text/css">
		#footer
		{
			width: 1000px;	height: 60px;
			background-color: #8e8e8e;
			margin-top: 0px;
			border-radius: 0px 0px 10px 10px;
			box-shadow: 0px 0px 10px #000000 inset;
			position: relative;
		}
		.footer_elements{position: relative;}
		#copywritght_tag
		{
			min-width: 0px;	min-height: 0px;
			color: #ffffff;
			top:20px;	left: 20px;
			display: inline;
		}
		#social_band
		{
			margin: -18px auto;
			display: table;
		}
		#social_band ul{list-style-type: none; 	display: inline-flex; padding: 0px;}
		#social_band ul li{display: inline-flex;}
		#social_band ul li a img{height: 32px;	width: 32px;}
		
	</style>
</head>

<div id="footer">
	<div id="copywritght_tag" class="footer_elements">&copy; Reinforce 2014,SRM University</div>
	<div id="social_band" class="footer_elements">
		<ul>
			<li>		<a href="http://www.facebook.com/">		<img src="./imgs/social_icons/fb.png">		</a>		</li>
			<li>		<a href="http://www.twitter.com/">		<img src="./imgs/social_icons/twitter.png">	</a>		</li>
			<li>		<a href="http://www.youtube.com/">		<img src="./imgs/social_icons/youtube.png">	</a>		</li>
		</ul>
	</div>
</div>