<head>
	<style type="text/css">
		#header
		{
			width: 1000px;	height: 100px;
			background-color: #8e8e8e;
			margin: auto;
			box-shadow: 0px 0px 10px #000000 inset;
		}
		#logo
		{
			background: url('./imgs/logo.png') no-repeat center center / 100% 100% transparent;
			height: 80px;	width: 100px;
			position: relative;
			top:10px;	left: 10px;
		}
		#head_text
		{
			position: relative;
			margin: -70px auto;
			width: 400px;	height: 80px;
		}
		#srm_logo
		{
			position: relative;
			left: 830px;	top: -10px;
			background: url('./imgs/srmlogo.png') no-repeat center center / 100% 100% transparent;
			height: 80px;	width: 160px;
		}

	</style>
</head>
<div id="header">
	<a href="./index.php" style="height:100%; width:100%"><div id="logo"></div></a>
	<div id="head_text"></div>
	<a href="http://www.srmuniv.ac.in" style="height:100%; width:100%" target="_blank"><div id="srm_logo"></div></a>
</div>