<head>
	<style type="text/css">
		#navigation_wrapper
		{
			float: right;
			min-height: 0px;	width: 150px;
			position: relative;
			margin-top: 120px;
			z-index: 100;
		}

		#navigation_container ul{list-style-type: none;}
		#navigation_container ul li{list-style-type: none; padding: 5px	0px;}
		#navigation_container ul li a{text-decoration: none;}

		.nav_list_elements
		{
			width: 100%;
			padding: 3px 0px;
			background-color: #b70101;
			color: #ffffff;
			border-radius: 5px 0px 0px 5px;
			border: 3px ridge	#000000;
			text-align: center;
			box-shadow: -3px 0px 3px #323232;

		}

	</style>

</head>
<div id="navigation_wrapper">
	<div id="navigation_container">
		<ul>
			<li>	<a href="index.php">	<div id="home" class="nav_list_elements">		HOME 		</div>	</a>	</li>
			<li>	<a href="about_us.php">	<div id="about_us" class="nav_list_elements">	ABOUT US 	</div>	</a>	</li>
			<li>	<a href="events.php">	<div id="events" class="nav_list_elements">		EVENTS 		</div>	</a>	</li>
			<li>	<a href="team.php">		<div id="team" class="nav_list_elements">		TEAM		</div>	</a>	</li>
			<li>	<a href="contact.php">	<div id="contact" class="nav_list_elements">	CONTACT US 	</div>	</a>	</li>
		</ul>
	</div>
</div>